create database vet_clinic;

CREATE TABLE animals (
	id INT GENERATED By Default AS IDENTITY,
	name VARCHAR(25),
	date_of_birth DATE,
	escape_attempts INT,
	neutered BOOLEAN,
	weight_kg DECIMAL,
	PRIMARY KEY(id)
);

ALTER TABLE animals ADD species VARCHAR(25);

CREATE TABLE owners (
	id SERIAL PRIMARY KEY, 
	full_name VARCHAR, 
	age INT
);

CREATE TABLE species (
	id SERIAL PRIMARY KEY, 
	name VARCHAR);

ALTER TABLE animals 
	ADD owner_id INT;

ALTER TABLE animals 
  DROP COLUMN species;

ALTER TABLE animals
  ADD COLUMN species_id INT REFERENCES species(id);

ALTER TABLE animals
  ADD COLUMN owner_id INT REFERENCES owners(id);

-- Create vets table
CREATE TABLE vets (
    id SERIAL NOT NULL,
    name VARCHAR(100) NOT NULL,
    age SMALLINT,
    date_of_graduation DATE,
    PRIMARY KEY (id)
);

-- Create specializations table
CREATE TABLE specializations  (
    id SERIAL NOT NULL,
    vet_id INT,
    specie_id INT,
    PRIMARY KEY (id)
);

-- Create visits table
CREATE TABLE visits  (
    id SERIAL NOT NULL,
    animal_id INT,
    vet_id INT,
    date_of_visit DATE,
    PRIMARY KEY (id)
);

-- Add index "animal_id" to visits table
CREATE INDEX visits_idx_animal_id ON "visits" ("animal_id");

-- Add index "vet_id" to visits table
CREATE INDEX visits_idx_vet_id ON "visits" ("vet_id");

-- Add index "email" to owners table
CREATE INDEX owner_idx_email ON "owners" ("email"); 