create database vet_clinic;

CREATE TABLE animals (
	id INT GENERATED By Default AS IDENTITY,
	name VARCHAR(25),
	date_of_birth DATE,
	escape_attempts INT,
	neutered BOOLEAN,
	weight_kg DECIMAL,
	PRIMARY KEY(id)
);

ALTER TABLE animals ADD species VARCHAR(25);

CREATE TABLE owners (
	id SERIAL PRIMARY KEY, 
	full_name VARCHAR, 
	age INT
);

CREATE TABLE species (
	id SERIAL PRIMARY KEY, 
	name VARCHAR);

ALTER TABLE animals 
	ADD owner_id INT;

ALTER TABLE animals 
  DROP COLUMN species;

ALTER TABLE animals
  ADD COLUMN species_id INT REFERENCES species(id);

ALTER TABLE animals
  ADD COLUMN owner_id INT REFERENCES owners(id);

-- Create Vets table
CREATE TABLE vets (
    id SERIAL NOT NULL,
    name VARCHAR(100) NOT NULL,
    age SMALLINT,
    date_of_graduation DATE,
    PRIMARY KEY (id)
);
